# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Session-PHP
version:      0.05
version_from: lib/Apache/Session/PHP.pm
installdirs:  site
requires:
    Apache::Session:               1.52
    PHP::Session:                  0.06
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
